from .voice_swap_node import NODE_CLASS_MAPPINGS as _VOICE_SWAP_NODES, NODE_DISPLAY_NAME_MAPPINGS as _VOICE_SWAP_NAMES
from .voice_room_match_node import NODE_CLASS_MAPPINGS as _ROOM_MATCH_NODES, NODE_DISPLAY_NAME_MAPPINGS as _ROOM_MATCH_NAMES

NODE_CLASS_MAPPINGS = {**_VOICE_SWAP_NODES, **_ROOM_MATCH_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_VOICE_SWAP_NAMES, **_ROOM_MATCH_NAMES}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
